spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      retries: 0
      batch-size: 16384
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # ?????????json??
      value-serializer: org.springframework.kafka.support.serializer.StringSerializer

    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumer1
      # ???????offset??????(????????????????)
      auto-offset-reset: earliest

kafka:
  topic:
    my-topic1: TOPIC1
    my-topic2: TOPIC2
