spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: mysql123
      url: jdbc:mysql://121.41.169.208:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
#  security:
#    user:
#      name: user
#      password: 123456
mybatis:
  type-aliases-package: com.hlq.mybatis.entity
  mapper-locations: classpath:mapper/*Mapper.xml