kafka:
  topic: TOPIC-TEST

  producer:
    broker_list:  172.24.37.136:9092
    client_id: hanlinqi
    acks: all

  consumer:
    broker_list: localhost:9092
    group_id: group1
    auto_offset_reset: earliest

#spring:
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      acks: all
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group1
#      auto-offset-reset: earliest
#    template:
#      default-topic: TOPIC-TEST