#version: '3.7'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    volumes:
#      - ./zookeeper-logs:/data
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#    expose:
#      - 2181
#
#
#  kafka_node1:
#    image: wurstmeister/kafka
#    volumes:
#      - ./kafka-logs:/kafka
#    ports:
#      - "9092:9092"
#    container_name: kafka_node1
#    environment:
#      KAFKA_BROKER_ID: 0
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
#    depends_on:
#      - zookeeper
#    expose:
#      - 9092

#  # Kafka Web管理界面
#  kafka_manager:
#    image: 'hlebalbau/kafka-manager:latest'
#    ports:
#      - "9000:9000"
#    environment:
#      ZK_HOSTS: "zookeeper:2181"
#      APPLICATION_SECRET: letmein
#    depends_on:
#      - zookeeper
#      - kafka_node1

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
